import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { JSDOM, VirtualConsole } from 'jsdom';
import assert from 'node:assert/strict';

const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', error => { if (!/Could not load link|HTMLCanvasElement/.test(error.message)) console.error(error.message); });
const dom = await JSDOM.fromFile(fileURLToPath(new URL('../index.html', import.meta.url)), { runScripts: 'dangerously', resources: 'usable', virtualConsole });
await new Promise(resolve => dom.window.addEventListener('load', () => setTimeout(resolve, 250), { once: true }));
const { document } = dom.window;
assert.ok(document.querySelector('#workspace-rail'), 'workspace rail mounted');
assert.ok(document.querySelector('#workspace-context'), 'workspace context mounted');
for (const id of ['asml', 'micron', 'swancor', 'skyeuv']) assert.ok(document.querySelectorAll(`#section-${id} .qa-card`).length > 0, `${id} questions rendered`);
assert.equal(document.querySelectorAll('[onclick],[oninput]').length, 0, 'no inline handlers');
const ids = [...document.querySelectorAll('.qa-card[data-question-id]')].map(card => card.dataset.questionId);
assert.equal(ids.length, new Set(ids).size, 'runtime question IDs unique');
assert.equal(dom.window.InterviewState?.state.schemaVersion, 2);
assert.equal(dom.window.InterviewQuestionRegistry?.schemaVersion, 1);
assert.ok(Object.keys(dom.window.InterviewQuestionRegistry?.companies || {}).length >= 7, 'all company banks normalized');
const axeSource = fs.readFileSync(new URL('../node_modules/axe-core/axe.min.js', import.meta.url), 'utf8');
dom.window.eval(axeSource);
const axeResults = await dom.window.axe.run(document, { runOnly: ['wcag2a', 'wcag2aa'] });
const serious = axeResults.violations.filter(violation => ['critical', 'serious'].includes(violation.impact));
assert.equal(serious.length, 0, `axe critical/serious violations: ${serious.map(v => v.id).join(', ')}`);
dom.window.close();
console.log('Browser smoke passed.');
