import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const listeners = {};
const window = { addEventListener: (name, fn) => { listeners[name] = fn; }, dispatchEvent: () => {} };
const document = { querySelectorAll: () => [], getElementById: () => null, addEventListener: () => {} };
const localStorage = { getItem: key => key === 'interview-workspace-state' ? JSON.stringify({ schemaVersion: 2, activeCompanyId: 'assembly', questions: { 'assembly.tech.q01': { mastered: true, attemptedCount: 2 }, 'skyeuv.tech.legacy01': { mastered: true, attemptedCount: 2 } }, practiceHistory: [{ questionId: 'assembly.tech.q01', at: '2026-08-01T00:00:00.000Z' }, { questionId: 'skyeuv.tech.legacy01', at: '2026-08-01T00:00:00.000Z' }] }) : null, setItem: () => { throw new Error('storage disabled'); } };
const map = { 'skyeuv.tech.legacy01': 'skyeuv.tech.q01' };
const context = vm.createContext({ window, document, localStorage, CustomEvent: class {}, console, LegacyQuestionIdMap: map });
window.LegacyQuestionIdMap = map;
vm.runInContext(fs.readFileSync(new URL('../js/state.js', import.meta.url), 'utf8'), context);
listeners.DOMContentLoaded?.();
assert.equal(window.InterviewState.state.schemaVersion, 2);
assert.equal(window.InterviewState.state.activeCompanyId, 'lam');
assert.equal(window.InterviewState.getQuestion('assembly.tech.q01').mastered, true, 'Assembly mastery survives lifecycle migration');
assert.equal(window.InterviewState.getQuestion('skyeuv.tech.q01').mastered, true);
const record = window.InterviewState.toggle('benq.tech.spc-purpose');
assert.equal(record.mastered, true);
assert.equal(record.attemptedCount, 1);
assert.equal(record.practiceCount, 1);
assert.ok(record.lastPracticedAt);
assert.equal(window.InterviewState.getQuestion('benq.tech.spc-purpose').mastered, true);
assert.equal(window.InterviewState.state.practiceHistory.length, 3);
assert.equal(window.InterviewState.state.practiceHistory[0].questionId, 'assembly.tech.q01', 'Assembly practice history survives lifecycle migration');
console.log('State schema smoke passed.');
