import fs from 'node:fs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const state = fs.readFileSync(new URL('../js/state.js', import.meta.url), 'utf8');
const legacy = fs.readFileSync(new URL('../js/legacy-data.js', import.meta.url), 'utf8');
assert.match(html, /id="section-(asml|assembly|fstech|benq)"/);
assert.match(html, /section-benq/);
assert.match(html, /rel="icon"[^>]+interview-app\.jpg/);
assert.match(html, /js\/legacy-sections\.js/);
for (const id of ['asml', 'micron', 'swancor', 'skyeuv']) assert.match(legacy, new RegExp(`"${id}"`));
const questionIds = [...legacy.matchAll(/"id":"([^"]+)"/g)].map(match => match[1]).filter(id => id.split('.').length >= 3);
assert.ok(questionIds.length >= 180, 'legacy question inventory is present');
assert.equal(new Set(questionIds).size, questionIds.length, 'legacy question IDs are unique');
assert.match(state, /schemaVersion:\s*2/);
assert.doesNotMatch(state, /interview-mastered-\$\{index\}/);
assert.doesNotMatch(html, /interview-mastered-\$\{index\}/);
assert.doesNotMatch(html, /localStorage\.setItem\('interview-active-company'/);
assert.match(state, /migrateLegacy/);
assert.match(html, /prefers-reduced-motion/);
assert.match(state, /global-search-results/);
assert.match(state, /resetProgress/);
assert.match(html, /data-action="status-filter"/);
assert.match(html, /workspace-notice/);
assert.match(html, /aria-label/);
assert.match(html, /Content-Security-Policy/);
assert.doesNotMatch(html, /function preparePrint/);
assert.doesNotMatch(html, /\bonclick\s*=/i);
assert.doesNotMatch(html, /\boninput\s*=/i);
const cdnCount = (html.match(/https:\/\/cdn\.tailwindcss\.com/g) || []).length;
assert.equal(cdnCount, 0, 'runtime Tailwind CDN must not be required');
assert.ok(fs.existsSync(new URL('../assets/tailwind.generated.css', import.meta.url)), 'generated CSS is present');
execFileSync(process.execPath, ['--check', 'js/state.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['--check', 'js/legacy-sections.js'], { stdio: 'inherit' });
execFileSync(process.execPath, ['--check', 'js/legacy-data.js'], { stdio: 'inherit' });
console.log('Interview workspace validation passed.');
