import fs from 'node:fs';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';

const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const state = fs.readFileSync(new URL('../js/state.js', import.meta.url), 'utf8');
assert.match(html, /id="section-(asml|assembly|fstech|benq)"/);
assert.match(html, /section-benq/);
assert.match(state, /schemaVersion:\s*2/);
assert.doesNotMatch(state, /interview-mastered-\$\{index\}/);
assert.doesNotMatch(html, /interview-mastered-\$\{index\}/);
assert.doesNotMatch(html, /localStorage\.setItem\('interview-active-company'/);
assert.match(state, /migrateLegacy/);
assert.match(html, /prefers-reduced-motion/);
assert.match(html, /aria-label/);
assert.match(html, /Content-Security-Policy/);
assert.doesNotMatch(html, /function preparePrint/);
const cdnCount = (html.match(/https:\/\/cdn\.tailwindcss\.com/g) || []).length;
assert.equal(cdnCount, 0, 'runtime Tailwind CDN must not be required');
assert.ok(fs.existsSync(new URL('../assets/tailwind.generated.css', import.meta.url)), 'generated CSS is present');
execFileSync(process.execPath, ['--check', 'js/state.js'], { stdio: 'inherit' });
console.log('Interview workspace validation passed.');
